### ISSUE TITLE
Graphyne Server 1.0 Roadmap

### ISSUE THREAD

**Issue by hoangvvo** [hoangvvo/graphyne#1]
This issue is for me to keep track of my plan to move `graphyne` toward 1.0. Feel free to chime in!

- [ ] Subscription support
- [ ] Dataloader integration (1 + N Problems)
- [ ] Persisted queries
- [ ] File Upload (inbuilt or optional)
- [ ] Caching Header API for CDN

**Comment by hoangvvo** [comment]
`Dataloader integration` and `File Upload` is already covered in our [guides](https://github.com/hoangvvo/graphyne/labels/guide).

**Comment by hoangvvo** [comment]
#graphyne run benchmark

**Comment by hoangvvo** [comment]
#graphyne run benchmark
